export const planets = [
  {
    id: "wasp39b",
    name: "WASP-39 b",
    type: "Hot Saturn",
    distance: "700 light-years",
    temperature: "1200K",
    description: "The star of JWST's first exoplanet results. First planet where CO₂ was definitively detected in an exoplanet atmosphere.",
    color: "#f97316",
    data: [
      { wavelength: 0.6, transitDepth: 1.85 },
      { wavelength: 0.7, transitDepth: 1.90 },
      { wavelength: 0.8, transitDepth: 1.88 },
      { wavelength: 0.9, transitDepth: 1.92 },
      { wavelength: 1.0, transitDepth: 1.89 },
      { wavelength: 1.1, transitDepth: 1.91 },
      { wavelength: 1.2, transitDepth: 1.94 },
      { wavelength: 1.4, transitDepth: 2.10 },
      { wavelength: 1.6, transitDepth: 1.95 },
      { wavelength: 1.8, transitDepth: 1.93 },
      { wavelength: 2.0, transitDepth: 1.91 },
      { wavelength: 2.7, transitDepth: 2.15 },
      { wavelength: 3.0, transitDepth: 1.96 },
      { wavelength: 3.6, transitDepth: 2.05 },
      { wavelength: 4.3, transitDepth: 2.45 },
      { wavelength: 4.5, transitDepth: 2.20 },
      { wavelength: 5.0, transitDepth: 2.08 },
    ],
    molecules: [
      { name: "H₂O", wavelength: 1.4, color: "#3b82f6", description: "Water vapor — detected strongly, hints at a cloudy atmosphere" },
      { name: "H₂O", wavelength: 2.7, color: "#3b82f6", description: "Water vapor — second major absorption band" },
      { name: "CO₂", wavelength: 4.3, color: "#ef4444", description: "Carbon dioxide — historic first definitive CO₂ detection on any exoplanet by JWST (2022)" },
      { name: "SO₂", wavelength: 4.0, color: "#a855f7", description: "Sulfur dioxide — unexpected discovery, likely from photochemistry in the upper atmosphere" },
    ],
  },
  {
    id: "hatp18b",
    name: "HAT-P-18 b",
    type: "Hot Jupiter",
    distance: "540 light-years",
    temperature: "850K",
    description: "A cooler hot Jupiter with a surprisingly rich atmosphere. JWST detected water, CO₂ and even hints of cloud layers.",
    color: "#06b6d4",
    data: [
      { wavelength: 0.6, transitDepth: 2.20 },
      { wavelength: 0.7, transitDepth: 2.22 },
      { wavelength: 0.8, transitDepth: 2.21 },
      { wavelength: 0.9, transitDepth: 2.25 },
      { wavelength: 1.0, transitDepth: 2.23 },
      { wavelength: 1.1, transitDepth: 2.24 },
      { wavelength: 1.2, transitDepth: 2.28 },
      { wavelength: 1.4, transitDepth: 2.55 },
      { wavelength: 1.6, transitDepth: 2.30 },
      { wavelength: 1.8, transitDepth: 2.27 },
      { wavelength: 2.0, transitDepth: 2.24 },
      { wavelength: 2.7, transitDepth: 2.50 },
      { wavelength: 3.0, transitDepth: 2.30 },
      { wavelength: 3.6, transitDepth: 2.38 },
      { wavelength: 4.3, transitDepth: 2.70 },
      { wavelength: 4.5, transitDepth: 2.45 },
      { wavelength: 5.0, transitDepth: 2.35 },
    ],
    molecules: [
      { name: "H₂O", wavelength: 1.4, color: "#3b82f6", description: "Water vapor — strong detection across multiple bands" },
      { name: "H₂O", wavelength: 2.7, color: "#3b82f6", description: "Water vapor — second absorption band" },
      { name: "CO₂", wavelength: 4.3, color: "#ef4444", description: "Carbon dioxide — clear feature, atmosphere is carbon-rich" },
    ],
  },
  {
    id: "wasp96b",
    name: "WASP-96 b",
    type: "Hot Giant",
    distance: "1150 light-years",
    temperature: "1300K",
    description: "Featured in JWST's very first science images release. Has a remarkably clear, cloud-free atmosphere — rare among hot Jupiters.",
    color: "#22c55e",
    data: [
      { wavelength: 0.6, transitDepth: 1.70 },
      { wavelength: 0.7, transitDepth: 1.72 },
      { wavelength: 0.8, transitDepth: 1.71 },
      { wavelength: 0.9, transitDepth: 1.74 },
      { wavelength: 1.0, transitDepth: 1.72 },
      { wavelength: 1.1, transitDepth: 1.73 },
      { wavelength: 1.2, transitDepth: 1.76 },
      { wavelength: 1.4, transitDepth: 2.20 },
      { wavelength: 1.6, transitDepth: 1.80 },
      { wavelength: 1.8, transitDepth: 1.77 },
      { wavelength: 2.0, transitDepth: 1.74 },
      { wavelength: 2.7, transitDepth: 2.10 },
      { wavelength: 3.0, transitDepth: 1.82 },
      { wavelength: 3.6, transitDepth: 1.90 },
      { wavelength: 4.3, transitDepth: 2.00 },
      { wavelength: 4.5, transitDepth: 1.95 },
      { wavelength: 5.0, transitDepth: 1.88 },
    ],
    molecules: [
      { name: "H₂O", wavelength: 1.4, color: "#3b82f6", description: "Water vapor — exceptionally clear detection due to cloud-free atmosphere" },
      { name: "H₂O", wavelength: 2.7, color: "#3b82f6", description: "Water vapor — second band, very prominent" },
      { name: "CO₂", wavelength: 4.3, color: "#ef4444", description: "Carbon dioxide — moderate feature" },
    ],
  },
];
